name: CI

'on':
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # full history for metadata
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Python install
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install "ltd-conveyor<2.0.0"
          python -m pip install -r operations_milestones/requirements.txt

      - name: Build
        shell: bash
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
        run: |
          make html

      - name: Upload
        env:
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
        run: |
          ltd upload --gh --dir _build/html --product rtn-064


