name: CI

'on': [push, pull_request, workflow_dispatch]

jobs:
  call-workflow:
    uses: lsst-sqre/rubin-sphinx-technote-workflows/.github/workflows/ci.yaml@v1
    with:
      handle: rtn-064
    secrets:
      ltd_username: ${{ secrets.LTD_USERNAME }}
      ltd_password: ${{ secrets.LTD_PASSWORD }}
      JIRA_USER: ${{ secrets.JIRA_USER }}
      JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }}
